steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'donate_endpoint', '--trigger-http', '--runtime', 'python37', '--entry-point', 'donate_endpoint']
    dir: 'function/dir/from/repo/root'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'add_cof', '--trigger-http', '--runtime', 'python37', '--entry-point', 'add_cof']
    dir: 'function/dir/from/repo/root'
